### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW-Archive/LeatherEngine-HTML5#1]
So uhhh I tried to use html it just says page not found

**Comment by SanicBTW** [comment]
i still have to fix some stuff in order to get the thing playable, if you want to play it right now no matter the bugs and nothing else just tell me

**Comment by fnfporterhi** [comment]
can I? I don’t want to put pressure on you to fix it as fast as you can, and I don’t care about the bugs, many things have bugs.

**Comment by SanicBTW** [comment]
thats true, i will make the page now for an early test for now and i will eventually fix stuff, brb

**Comment by SanicBTW** [comment]
Page is up! https://sanicbtw.github.io/LeatherEngine-HTML5/

**Comment by SanicBTW** [comment]
Before any bug report check https://github.com/SanicBTW/LeatherEngine-HTML5/blob/source-code/README.md in order to see if your bug is in the list of pending to fix
