### ISSUE TITLE
Bug Report: game crashes after pressing enter

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW-Archive/LeatherEngine-HTML5#2]
I loaded this up the other day, and when I loaded it, I pressed enter to go to the menu, it crashed after I pressed enter.... did I do something wrong?

**Comment by SanicBTW** [comment]
Free play menu?

**Comment by fnfporterhi** [comment]
no, it’s just after it loads, and before it goes into main menu

**Comment by SanicBTW** [comment]
just reload the page and it will work fine again lol (first time crashes and idk which is the error because i dont have devtools and also too lazy to fix for now) maybe ill look into it tomorrow or something

**Comment by fnfporterhi** [comment]
ah ok thanks


just one question: what platform do you port on? windows or Chromebook?

**Comment by SanicBTW** [comment]
both actually, i work on windows for windows and android ports and on chromebook for html5 ports
